- name: This is configuring the catalogue service
  hosts: catalogue
  become: yes
  tasks:
  - name: installing the nodejs repos
    ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  
  - name: installing the nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed
  
  - name: checking the user
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true


  - name: Creating the user
    ansible.builtin.user:
      name: roboshop
      state: present    
    when: output.rc != 0
  
  - name: Check if the directory exists
    ansible.builtin.stat:
      path: /app
    register: dir_check
    ignore_errors: true


  - name: Create the directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: dir_check.stat.exists == False

  - name: Download the catalogue files
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip
  
  - name: Change the working directory to somedir/ before executing the command
    ansible.builtin.shell:
    args:
      chdir: /app