- name: This is the configurattion for redis server
  hosts: redis
  become: yes
  tasks:
  - name: Installing the redis repo file 
    ansible.builtin.yum_repository:
      name: remi
      description: redis remi repo
      baseurl: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: present
  
  - name: enabling the required package
    ansible.builtin.yum:
      name: remi
      enablerepo: "redis:remi-6.2"

  - name: installing redis
    ansible.builtin.yum:
      name: redis
      state: installed

  