- name: This is the configurattion for redis server
  hosts: redis
  become: yes
  tasks:
  - name: Installing the redis repo file 
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
  
  - name: enabling the remi 6.2
    ansible.builtin.yum:
      name: redis
      enablerepo: "redis:remi-6.2"

  - name: installing the selected redis
    ansible.builtin.yum:
      name: redis
      state: installed 
       