- name: This is the configurattion for redis server
  hosts: redis
  become: yes
  tasks:
  - name: Installing the redis repo file 
    ansible.builtin.yum:
      name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
      state: installed
      disable_gpg_check: true
  
  - name: Enable the remi 6.2 module
    ansible.builtin.command: yum module enable redis:remi-6.2 -y


  - name: installing redis
    ansible.builtin.yum:
      name: redis
      state: installed

  