- name: This is to configure the shipping module
  hosts: shipping
  become: yes
  tasks:
  - name: Installing the maven
    ansible.builtin.yum:
      name: maven
      state: installed
 
  - name: checking the user
    ansible.builtin.command: id roboshop
    register: output
    ignore_errors: true


  - name: Creating the user
    ansible.builtin.user:
      name: roboshop
      state: present    
    when: output.rc != 0
  
  - name: Check if the directory exists
    ansible.builtin.stat:
      path: /app
    register: dir_check
    ignore_errors: true


  - name: Create the directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: dir_check.stat.exists == False

  - name: Download the shipping files
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: Unarchive a file that is already on the remote machine
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes

  - name: installing dependencies
    ansible.builtin.command: mvn clean package
    args:
      chdir: /app

  - name: installing dependencies
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app
  - name: copying the shipping service file
    ansible.builtin.copy: 
      src: /home/centos/roboshop-ansible/shipping.service
      dest: /etc/systemd/system/shipping.service

  - name: daemon reload shipping
    ansible.builtin.systemd:
      daemon_reload: true
      name: shipping

    - name: enabling the shipping
      ansible.builtin.service:
        name: shipping
        enabled: yes
        state: restarted

    - name: installing mysql
      ansible.builtin.yum:
        name: mysql
        state: installed

    - name: loading the schema
      ansible.builtin.command: mysql -h mysql.saikiransudhireddy.com -uroot -pRoboShop@1 < /app/schema/shipping.sql 

    - name: restarting the shipping
      ansible.builtin.service:
        name: shipping
        state: restarted
